### ISSUE TITLE
Pulling in image from a resource?

### ISSUE THREAD

**Issue by vrurg** [pdf-raku/PDF-API6#16]
I have a document coming from a scanner with the following structure:

```
% **** Page 1 ****
q
  608.4 0 0 789.12 0 0 cm
  /FXX1 Do
Q
% **** Page 2 ****
q
  605.52 0 0 787.68 0 0 cm
  /FXX1 Do
Q
% **** Page 3 ****
q
  605.16 0 0 790.56 0 0 cm
  /FXX1 Do
Q
```

`FXX1` here is the image itself. `$gfx.images` doesn't see it. Is there a way to pull it out somehow and save into a PNG or whatever?

**Comment by dwarring** [comment]
This PDF has image resources, rather than inline images. If every page has an image resource named `FFX1`, then to get at the raw image data:
```raku
use PDF::API6;
use PDF::XObject::Image;

my PDF::API6 $pdf .= open: "test.pdf";

my $n := $pdf.page-count;
my PDF::XObject::Image @images = (1 .. $n).map: -> $page-num {
    $pdf.page($page-num)<Resources><XObject><FXX1>;
}

with @images.head -> $img {
    my blob8 $raw-compressed = $img.encoded.encode('latin-1');
    my blob8 $raw-uncompressed = $img.decoded;
    # partially implemented. probably returns Nil
    note (try $img.to-png1).WHAT.raku;
}
```

However, a PDF may contain several image formats, and the `to-png` is only partially implemented for some image formats. It will most likely return Nil rather than an object of `PDF::Content::Image::PNG`. It could be that image magick, or other image manipulation libraries can load the raw compressed or uncompressed data.

Reading of images from PDF files could, in general, do with a lot more work. I'd been thing of trying to integrate MagicWand, or something similar, but would need to investigate further.

**Comment by vrurg** [comment]
Thank you! I expected the format to be anything but hoped that perhaps PDF::To::Cairo can manage it. But with the current state of affairs it looks like using something like `pdftoppm` would be preferable.

BTW, unrelated. A while ago I desperately wanted to intercept PDF rendering to pull out data from it. No idea how I managed to overlook PDF::API6 being capable of this, but at the moment I'm biting own elbows seeing the possibilities I would have!

**Comment by dwarring** [comment]
`pdftoppm` Sound reasonable.

Yeah PDF::To::Cairo is just an advanced application of rendering also available in PDF::API6. PDF::Tags::Reader is another example that renders to extract structure and text from a tagged PDF file.
